### ISSUE TITLE
No manifest when blank installation

### ISSUE THREAD

**Issue by acailly** [stripedpajamas/scat#29]
I just tried to install scat on a Windows machine with no previous Patchwork or other ssb client and scat does not start.

The error message is `Uncaught exception, exiting :(`.

By catching the exception with

```
try{
	require('ssb-chat')
}
catch(e){
	console.error(e)
}
```

It seems that the problem is related to the `manifest.json` file which should be in a `.ssb` folder in the home directory:

```
Connecting to scuttlebot...
Error: could not load manifest file
    at C:\Projets\exp\ssb-chat\node_modules\ssb-client\index.js:75:13
    at tryModuleLoad (module.js:505:12)
  Error: ENOENT: no such file or directory, open 'C:\Users\90021245\.ssb\manifest.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at C:\Projets\exp\ssb-chat\node_modules\ssb-client\index.js:70:28
    at module.exports (C:\Projets\exp\ssb-chat\node_modules\ssb-client\index.js:77:5)
    at tryConnect (C:\Projets\exp\ssb-chat\node_modules\ssb-chat\util\client\index.js:16:3)
    at Object.start (C:\Projets\exp\ssb-chat\node_modules\ssb-chat\util\client\index.js:41:5)
    at Object.<anonymous> (C:\Projets\exp\ssb-chat\node_modules\ssb-chat\index.js:40:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

I tried to find some documentation about how to have a manifest file without installing another ssb client with no success.

Does it means that to run scat you should have an existing ssb client? Or maybe I missed something? :smiley:

**Comment by stripedpajamas** [comment]
Yeah-- it currently doesn't work if it's the first ssb client on a machine. I haven't dug into it to figure out why that is yet. Right now your only way forward is to run something like Patchwork once and then scat works.

**Comment by acailly** [comment]
Ok thank you

**Comment by stripedpajamas** [comment]
This issue should be fixed now (issue was upstream in [core](https://github.com/stripedpajamas/ssb-chat-core))

I haven't released a new version with the fix, so you would have to run from source to get it. Will be releasing a new version within the next few days.
