### ISSUE TITLE
Could not connect to sbot 

### ISSUE THREAD

**Issue by tatecarson** [stripedpajamas/scat#40]
I get this error when attempting to connect to scat. Are there any prerequisites for running it that I might not have? I can use patchwork with no issues. Is there any way of testing to figure out what the issue might be? 

```
scat                                  
Connecting to scuttlebot...
Error: Could not connect to sbot
    at Timeout.setInterval [as _onTimeout] (/usr/local/lib/node_modules/ssb-chat/node_modules/ssb-chat-core/connect/client.js:75:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by stripedpajamas** [comment]
Hi @tatecarson -- I think some of scat's dependencies were out of date. I've recently upgraded them and pushed ssb-chat@1.7.4. If you install this latest version, do you still see this issue?
